"""Initial migration

Revision ID: ab9f93fe6d98
Revises: 
Create Date: 2025-03-17 05:45:40.579360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab9f93fe6d98'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_conversations_id', table_name='conversations')
    op.drop_table('conversations')
    op.add_column('users', sa.Column('created_at', sa.String(), nullable=False))
    op.add_column('users', sa.Column('username', sa.String(), nullable=False))
    op.alter_column('users', 'id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('users', 'google_access_token')
    op.drop_column('users', 'google_refresh_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_refresh_token', sa.VARCHAR(), nullable=True))
    op.add_column('users', sa.Column('google_access_token', sa.VARCHAR(), nullable=True))
    op.alter_column('users', 'id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('users', 'username')
    op.drop_column('users', 'created_at')
    op.create_table('conversations',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversations_id', 'conversations', ['id'], unique=False)
    # ### end Alembic commands ###
